version: "3.8"

services:
  front:
    image: game-front
    container_name: game-front-container
    build:
      context: ./client
    volumes:
      - frontend-build:/build

  back:
    image: game-back
    container_name: game-back-container
    build:
      context: ./server
    volumes:
      - frontend-build:/build
    ports:
      - "7001:7001"
    depends_on:
      - front
    deploy:
      resources:
        limits:
          memory: 120M
    restart: on-failure

volumes:
  frontend-build:
